# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true

  # Additional paths webpack should lookup modules
  additional_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: true  # Cache manifest for performance in production

  # Extract and emit a css file
  extract_css: true  # Extract CSS files for production

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css

development:
  <<: *default
  compile: true

  # Development server settings
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true
  public_output_path: packs-test

production:
  <<: *default
  compile: false  # Disable on-the-fly compilation in production
